### PR TITLE
Fix incorrect buffer scale

### PR DESCRIPTION
**Pull request by emersion**
Fixes part of  https://github.com/swaywm/swaylock/issues/166

### CODE REVIEW

**Comment by ChrisLane** [comment]
I can confirm that this has fixed the issue for me. Thanks!

**Comment by gari** [comment]
Not work for me.

swaylock start, but when press any key it's got crash

```
$ swaylock -v
swaylock version 1.5-12-gf0344bb (Feb 11 2021, branch 'makepkg')
```

* https://pastebin.com/qYvD6K2w

**Comment by emersion** [comment]
```
[3852604.262]  -> wl_shm_pool@31.create_buffer(new id wl_buffer@32, 0, 240, 295, 960, 0)
```

For some reason swaylock creates a buffer with height = 295.

**Comment by gari** [comment]
i have very strange scale factor:
```
$ swaymsg -t get_outputs | grep -i Scale
    "scale": 1.4492189884185791,
    "scale_filter": "linear",
    "scale": 1.4492189884185791,
    "scale_filter": "linear",
```

This could be the reason of this error?

**Comment by rzlourenco** [comment]
This PR partially fixes it for me. Logs: https://gist.github.com/rzlourenco/46a857546cb363a62685d07af68277eb
Now the screen locker shows up but quits if I press most letters. Backspace and enter seem to do their usual job, but pressing any letter or key or symbol will terminate the screen locker.

**Comment by LaserEyess** [comment]
This patch fixes this for me, this is all I have for my outputs

```
output DP-1 {
    pos 0 0
    res 2560x1440@144Hz
    adaptive_sync on
}
output DP-2 {
    pos 2560 -500
    transform 270
    res 2560x1440@144Hz
    adaptive_sync on
}
output DP-3 {
    pos 4000 -200
    res 3840x2160@60Hz
    adaptive_sync on
    scale 2
}
```

**Comment by emersion** [comment]
Merging because this fixes part of the issue.

**Pull request merged**
