### PR TITLE
Drop support for layer-shell

### PR DESCRIPTION
**Pull request by emersion**
Superseded by ext-session-lock-v1

### CODE REVIEW

**Comment by kennylevinsen** [comment]
When do we want to merge this?

**Comment by emersion** [comment]
Ideally, I'd like to merge & release #280 as a bugfix, then merge this.

**Comment by kennylevinsen** [comment]
Did not expect "merge & release #280 as a bugfix" to mean "in 5 minutes". :D

**Review by kennylevinsen — APPROVED** [review]
LGTM

**Pull request merged**
