### PR TITLE
move all *.c files in src/

### PR DESCRIPTION
**Pull request by gdamjan**

### CODE REVIEW

**Comment by ddevault** [comment]
Is there a reason for this?

**Comment by emersion** [comment]
I'm pretty happy with .c files in the root directory.

**Comment by gdamjan** [comment]
> Is there a reason for this?

(should've added that in the PR text.)

it makes the root directory less noisy, and easier to find either source code, or non-source-code files.

**Comment by ddevault** [comment]
No thanks.

**Comment by gdamjan** [comment]
> No thanks.

Is there a reason for this?

**Comment by ddevault** [comment]
It's more than there's *not* a good reason for this.

**Pull request closed without merging**
